#############################################################################
# Makefile for building: headunit
# Generated by qmake (1.07a) (Qt 3.3.2) on: Fri Jul  2 04:22:32 2004
# Project:  headunit.pro
# Template: app
# Command: $(QMAKE) -o Makefile headunit.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -W -O2  -DQT_NO_DEBUG
CXXFLAGS = -pipe -W -O2  -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/qt/3/mkspecs/linux-g++ -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib `xine-config --libs`
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = AudioBrowserScreen.h \
		AudioPlayerScreen.h \
		Button.h \
		FileItem.h \
		HeadUnit.h \
		MediaItem.h \
		MenuScreen.h \
		Screen.h \
		SelectionList.h \
		Skin.h \
		XineDVDPanel.h \
		XinePanel.h \
		XineVideo.h \
		XineVideoPanel.h \
		XineVisPanel.h
SOURCES = AudioBrowserScreen.cpp \
		AudioPlayerScreen.cpp \
		Button.cpp \
		FileItem.cpp \
		HeadUnit.cpp \
		MediaItem.cpp \
		MenuScreen.cpp \
		Screen.cpp \
		SelectionList.cpp \
		Skin.cpp \
		XineDVDPanel.cpp \
		XinePanel.cpp \
		XineVideo.cpp \
		XineVideoPanel.cpp \
		XineVisPanel.cpp
OBJECTS = AudioBrowserScreen.o \
		AudioPlayerScreen.o \
		Button.o \
		FileItem.o \
		HeadUnit.o \
		MediaItem.o \
		MenuScreen.o \
		Screen.o \
		SelectionList.o \
		Skin.o \
		XineDVDPanel.o \
		XinePanel.o \
		XineVideo.o \
		XineVideoPanel.o \
		XineVisPanel.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_AudioBrowserScreen.cpp \
		moc_AudioPlayerScreen.cpp \
		moc_SelectionList.cpp \
		moc_XinePanel.cpp \
		moc_XineVideo.cpp
OBJMOC = moc_AudioBrowserScreen.o \
		moc_AudioPlayerScreen.o \
		moc_SelectionList.o \
		moc_XinePanel.o \
		moc_XineVideo.o
DIST	   = headunit.pro
QMAKE_TARGET = headunit
DESTDIR  = 
TARGET   = headunit

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: headunit.pro  /usr/qt/3/mkspecs/linux-g++/qmake.conf 
	$(QMAKE) -o Makefile headunit.pro
qmake: 
	@$(QMAKE) -o Makefile headunit.pro

dist: 
	@mkdir -p .tmp/headunit && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/headunit/ && ( cd `dirname .tmp/headunit` && $(TAR) headunit.tar headunit && $(GZIP) headunit.tar ) && $(MOVE) `dirname .tmp/headunit`/headunit.tar.gz . && $(DEL_FILE) -r .tmp/headunit

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

AudioBrowserScreen.o: AudioBrowserScreen.cpp HeadUnit.h \
		AudioPlayerScreen.h \
		AudioBrowserScreen.h \
		SelectionList.h \
		FileItem.h \
		Skin.h \
		Screen.h \
		Button.h

AudioPlayerScreen.o: AudioPlayerScreen.cpp HeadUnit.h \
		MenuScreen.h \
		AudioPlayerScreen.h \
		AudioBrowserScreen.h \
		XineVideo.h \
		SelectionList.h \
		MediaItem.h \
		Skin.h \
		Button.h \
		Screen.h

Button.o: Button.cpp Button.h

FileItem.o: FileItem.cpp FileItem.h

HeadUnit.o: HeadUnit.cpp HeadUnit.h \
		MenuScreen.h \
		AudioPlayerScreen.h \
		AudioBrowserScreen.h \
		XineVideo.h \
		Button.h \
		Screen.h

MediaItem.o: MediaItem.cpp MediaItem.h

MenuScreen.o: MenuScreen.cpp HeadUnit.h \
		MenuScreen.h \
		AudioPlayerScreen.h \
		Skin.h \
		XineVideo.h \
		Button.h \
		Screen.h \
		SelectionList.h

Screen.o: Screen.cpp Screen.h

SelectionList.o: SelectionList.cpp SelectionList.h

Skin.o: Skin.cpp Button.h \
		SelectionList.h \
		Skin.h

XineDVDPanel.o: XineDVDPanel.cpp HeadUnit.h \
		MenuScreen.h \
		XineDVDPanel.h \
		Button.h \
		Screen.h \
		XinePanel.h

XinePanel.o: XinePanel.cpp HeadUnit.h \
		AudioPlayerScreen.h \
		MenuScreen.h \
		XinePanel.h \
		XineVideo.h \
		Skin.h \
		Screen.h \
		Button.h \
		SelectionList.h

XineVideo.o: XineVideo.cpp XineVisPanel.h \
		XineVideoPanel.h \
		XineDVDPanel.h \
		XineVideo.h \
		HeadUnit.h \
		MenuScreen.h \
		XinePanel.h \
		Screen.h \
		Button.h

XineVideoPanel.o: XineVideoPanel.cpp HeadUnit.h \
		MenuScreen.h \
		XineVideoPanel.h \
		Button.h \
		Screen.h \
		XinePanel.h

XineVisPanel.o: XineVisPanel.cpp HeadUnit.h \
		AudioPlayerScreen.h \
		XineVisPanel.h \
		Button.h \
		Screen.h \
		XinePanel.h

moc_AudioBrowserScreen.o: moc_AudioBrowserScreen.cpp  AudioBrowserScreen.h Screen.h

moc_AudioPlayerScreen.o: moc_AudioPlayerScreen.cpp  AudioPlayerScreen.h Screen.h

moc_SelectionList.o: moc_SelectionList.cpp  SelectionList.h 

moc_XinePanel.o: moc_XinePanel.cpp  XinePanel.h Screen.h

moc_XineVideo.o: moc_XineVideo.cpp  XineVideo.h Screen.h

moc_AudioBrowserScreen.cpp: $(MOC) AudioBrowserScreen.h
	$(MOC) AudioBrowserScreen.h -o moc_AudioBrowserScreen.cpp

moc_AudioPlayerScreen.cpp: $(MOC) AudioPlayerScreen.h
	$(MOC) AudioPlayerScreen.h -o moc_AudioPlayerScreen.cpp

moc_SelectionList.cpp: $(MOC) SelectionList.h
	$(MOC) SelectionList.h -o moc_SelectionList.cpp

moc_XinePanel.cpp: $(MOC) XinePanel.h
	$(MOC) XinePanel.h -o moc_XinePanel.cpp

moc_XineVideo.cpp: $(MOC) XineVideo.h
	$(MOC) XineVideo.h -o moc_XineVideo.cpp

####### Install

install:  

uninstall:  

